name: The Fuzz

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.8, 3.9, "3.10"]
        test-cmd: [pytest]
        include:
          #- python-version: pypy3.5-5.8.0
          #  test-cmd: pytest test_thefuzz.py test_thefuzz_pytest.py
          - python-version: 3.6
            test-cmd: python setup.py check --restructuredtext --strict --metadata
          - python-version: 3.8
            test-cmd: python setup.py check --restructuredtext --strict --metadata
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest pycodestyle docutils Pygments hypothesis python-Levenshtein
      - name: Test with pytest
        run: |
          ${{ matrix.test-cmd }}
